### ISSUE TITLE
Adding DP?

### ISSUE THREAD

**Issue by Quick-Eyed-Sky** [ai-prompts/prompt-lists#1]
You should add to your great tool Dynamic Prompting, like here: 
https://colab.research.google.com/drive/1hNmWnXnoNE9vXTujD3udJRSYTjSjowvV?usp=sharing

Dynamic Prompting is a simple trick that chooses randomly words in lists written like this: "Photo of a {car|train|truck} in the {sun|rain|evening|mist}

We should be able to save the big list of prompts to a .csv

**Comment by fofr** [comment]
You can structure prompts like this:
https://prompter.fofr.ai/?id=1b9f9b7e-cc2a-4665-8315-cd9cc413d752

```
Photo of a {[vehicle.type]|[vehicle.type]|[vehicle.type]} in the ...
```

Which outputs prompts like:

```
Photo of a {hybrid car|van|rocket} in the ...
```

**Comment by fofr** [comment]
I've added a download link:

<img width="950" alt="Screenshot 2023-06-14 at 11 00 53" src="https://github.com/ai-prompts/prompt-lists/assets/319055/5344916a-bdde-42ed-babf-1c706b06b6f1">
